ASG0002: ASGW Indoor-Dual Core-WiFi-LTE CAT4 EU
ASG0001: ASGW Indoor-Dual Core-WiFi
ASG0003: ASGW Indoor-Quad Core-WiFi-LTE CAT4 EU
ASG0006: ASGW Indoor-Dual Core-WiFi-LTE CAT4 AU
SRG0001: SolidSense N6 Edge Gateway Indoor - Dual Core-WiFi - Industrial
SRG0002: SolidSense N6 Edge Gateway Indoor - Dual Core-WiFi-LTE C4 EU - Industrial
SRG0003: SolidSense N6 Edge Gateway Indoor - Quad Core-WiFi -LTE C4 EU - Industrial
SRG0004: SolidSense N6 Edge Gateway Indoor - Dual Core-WiFi-LTE C4 US - Industrial
SRG0005: SolidSense N6 Edge Gateway Indoor - Single Core-WiFi-LTE C4 EU - Industrial
SRG0006: SolidSense N6 Edge Gateway Indoor - Dual Core-WiFi-LTE C4 AU - Industrial
SRG0007: SolidSense N6 Edge Gateway Indoor - Quad Core-WiFi-LTE C4 US - Industrial
SRG0102: SolidSense N6 Edge Gateway Outdoor - Dual Core-WiFi-LTE C4 EU - Industrial
SRG0107: SolidSense N6 EDGE Gateway Outdoor - Dual Core-WiFi-LTE C4 AU - Industrial
SRG0200: SolidSense N6 Industrial Edge Gateway - Dual Core - PCB version
SRG0201: SolidSense N6 Industrial Edge Gateway - Dual Core - No LTE
SRG0202: SolidSense N6 Industrial Edge Gateway - Dual Core - LTE EU
SRG0202: SolidSense N6 Industrial Edge Gateway - Dual Core - LTE Global
SRG0203: SolidSense N6 Industrial Edge Gateway - Dual Core - LTE AU
SRG0231: SolidSense N6 Industrial Ethernet Gateway - Dual Core
SRG0232: SolidSense N6 Industrial Ethernet Gateway - Dual Core - LTE Global
SRG0400: SolidSense N8 Compact - Test version fully equipped
SRG0401: SolidSense N8 Compact BLE
SRG0402: SolidSense N8 Compact LTE BLE
SRG0403: SolidSense N8 Compact Extended
SRG0404: SolidSense N8 Compact LTE Extended
SRG0405: SolidSense N8 Compact WiFi LTE Extended
